/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zhiweitong' at '17-6-6 下午1:06' with Gradle 2.3
 *
 * @author zhiweitong, @date 17-6-6 下午1:06
 */
public class Library {
	
    public boolean someLibraryMethod() {
    	
        return true;
    }
}
